In [34]:
import pandas as pd
import matplotlib.pyplot as plt

Código de sampleo para reducir volumen de datos: creación de nueva columna H, obtención de media de valores/hora y agrupación de filas por horas

In [35]:
dataset = 'dataset/preprocessed/new_power_samples_d4_1split_1.csv'

In [36]:
df = pd.read_csv(dataset)  

X = df.iloc[:, 3:18].values
print(X)

# # Calcular el promedio de los datos numéricos por hora
# hourly_data = df[param].resample('H').mean()

# # Agrupar los datos por hora y calcular la media
# hourly_data = df.resample('H').mean()

# # Guardar el nuevo dataset con un registro por hora
# hourly_data.to_csv('dataset_reducido.csv')  # Puedes cambiar el nombre del archivo de salida si lo deseas

[[0.954813 1.07339  1.03271  ... 0.990567 0.994678 0.992976]
 [1.00018  1.07347  1.03088  ... 0.990783 0.99445  0.992902]
 [0.982513 1.06635  1.02955  ... 0.990912 0.99485  0.992979]
 ...
 [1.14371  1.60793  1.51132  ... 0.891092 0.933694 0.925208]
 [1.40324  1.59205  1.55559  ... 0.913975 0.93348  0.928249]
 [0.96816  1.58097  1.24803  ... 0.91915  0.946461 0.938234]]

In [37]:
df['tmstp'] = pd.to_datetime(df['tmstp'])
df['H'] = df['tmstp'].dt.strftime('%H') #nueva columna de hora
df['H'] = df['H'].astype(int)

df.head(10)

,iid,tmstp,deploy,Imin,Imax,Iavg,Vmin,Vmax,Vavg,Pmin,...,Qmin,Qmax,Qavg,PFmin,PFmax,PFavg,miss_flag,datetime,hour,H
0,41,2013-07-31 16:52:56,4,0.954813,1.07339,1.03271,227.960,230.141,229.155,216.817,...,24.1588,33.0240,27.9611,0.990567,0.994678,0.992976,0,2013-07-31,16:52:56,16
1,41,2013-07-31 16:53:56,4,1.000180,1.07347,1.03088,228.510,229.776,229.121,227.470,...,24.6816,32.0705,28.0698,0.990783,0.994450,0.992902,0,2013-07-31,16:53:56,16
2,41,2013-07-31 16:54:56,4,0.982513,1.06635,1.02955,228.973,230.064,229.540,223.481,...,23.9864,31.6279,27.9242,0.990912,0.994850,0.992979,0,2013-07-31,16:54:56,16
3,41,2013-07-31 16:55:56,4,1.003140,1.06389,1.03003,228.963,230.052,229.552,228.489,...,24.5454,32.6138,27.9845,0.990684,0.994681,0.992956,0,2013-07-31,16:55:56,16
4,41,2013-07-31 16:56:56,4,1.000820,1.06505,1.02941,229.138,229.904,229.525,227.812,...,24.6690,31.9640,27.9914,0.991285,0.994395,0.992947,0,2013-07-31,16:56:56,16
5,41,2013-07-31 16:57:56,4,1.002030,1.06476,1.02952,228.916,229.941,229.434,228.107,...,24.9522,31.5040,27.8697,0.991280,0.994305,0.993006,0,2013-07-31,16:57:56,16
6,41,2013-07-31 16:58:56,4,0.997193,1.06155,1.02817,229.074,229.781,229.516,226.621,...,23.9253,31.5581,27.9942,0.990725,0.994786,0.992926,0,2013-07-31,16:58:56,16
7,41,2013-07-31 16:59:56,4,1.001340,1.06497,1.02646,229.243,230.142,229.763,228.167,...,24.7474,31.8224,28.0360,0.990933,0.994415,0.992894,0,2013-07-31,16:59:56,16
8,41,2013-07-31 17:00:56,4,0.998172,1.06761,1.02823,229.160,230.218,229.802,227.523,...,24.3302,31.2256,27.9664,0.991343,0.994670,0.992956,0,2013-07-31,17:00:56,17
9,41,2013-07-31 17:01:56,4,1.001140,1.06799,1.02761,229.293,230.079,229.727,228.122,...,24.7778,31.7747,28.1247,0.991124,0.994417,0.992865,0,2013-07-31,17:01:56,17

In [46]:
iid_uniques = df['iid'].unique() #ids que aparecen en el dataset
H_uniques = df['H'].unique() #array de horas

#for id in iid_uniques:
#    for h in H_uniques:

filter = df[(df['iid'] == 42) & (df['H'] == 0) & (df['datetime'] == '2013-07-31')]
filter

# hourly_data = df['Pavg'].resample('hour_H').mean()
# hourly_data

,iid,tmstp,deploy,Imin,Imax,Iavg,Vmin,Vmax,Vavg,Pmin,...,Qmin,Qmax,Qavg,PFmin,PFmax,PFavg,miss_flag,datetime,hour,H
334976,42,2013-07-31 00:00:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:00:00,0
334977,42,2013-07-31 00:01:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:01:00,0
334978,42,2013-07-31 00:02:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:02:00,0
334979,42,2013-07-31 00:03:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:03:00,0
334980,42,2013-07-31 00:04:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:04:00,0
334981,42,2013-07-31 00:05:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:05:00,0
334982,42,2013-07-31 00:06:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:06:00,0
334983,42,2013-07-31 00:07:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:07:00,0
334984,42,2013-07-31 00:08:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:08:00,0
334985,42,2013-07-31 00:09:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:09:00,0
334986,42,2013-07-31 00:10:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:10:00,0
334987,42,2013-07-31 00:11:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:11:00,0
334988,42,2013-07-31 00:12:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:12:00,0
334989,42,2013-07-31 00:13:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:13:00,0
334990,42,2013-07-31 00:14:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:14:00,0
334991,42,2013-07-31 00:15:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:15:00,0
334992,42,2013-07-31 00:16:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:16:00,0
334993,42,2013-07-31 00:17:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:17:00,0
334994,42,2013-07-31 00:18:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:18:00,0
334995,42,2013-07-31 00:19:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:19:00,0
334996,42,2013-07-31 00:20:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:20:00,0
334997,42,2013-07-31 00:21:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:21:00,0
334998,42,2013-07-31 00:22:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:22:00,0
334999,42,2013-07-31 00:23:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:23:00,0
335000,42,2013-07-31 00:24:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:24:00,0
335001,42,2013-07-31 00:25:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:25:00,0
335002,42,2013-07-31 00:26:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:26:00,0
335003,42,2013-07-31 00:27:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:27:00,0
335004,42,2013-07-31 00:28:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:28:00,0
335005,42,2013-07-31 00:29:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:29:00,0
335006,42,2013-07-31 00:30:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:30:00,0
335007,42,2013-07-31 00:31:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:31:00,0
335008,42,2013-07-31 00:32:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:32:00,0
335009,42,2013-07-31 00:33:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:33:00,0
335010,42,2013-07-31 00:34:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:34:00,0
335011,42,2013-07-31 00:35:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:35:00,0
335012,42,2013-07-31 00:36:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:36:00,0
335013,42,2013-07-31 00:37:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:37:00,0
335014,42,2013-07-31 00:38:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:38:00,0
335015,42,2013-07-31 00:39:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:39:00,0
335016,42,2013-07-31 00:40:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:40:00,0
335017,42,2013-07-31 00:41:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:41:00,0
335018,42,2013-07-31 00:42:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:42:00,0
335019,42,2013-07-31 00:43:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:43:00,0
335020,42,2013-07-31 00:44:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:44:00,0
335021,42,2013-07-31 00:45:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:45:00,0
335022,42,2013-07-31 00:46:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:46:00,0
335023,42,2013-07-31 00:47:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:47:00,0
335024,42,2013-07-31 00:48:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:48:00,0
335025,42,2013-07-31 00:49:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:49:00,0
335026,42,2013-07-31 00:50:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:50:00,0
335027,42,2013-07-31 00:51:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:51:00,0
335028,42,2013-07-31 00:52:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:52:00,0
335029,42,2013-07-31 00:53:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:53:00,0
335030,42,2013-07-31 00:54:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:54:00,0
335031,42,2013-07-31 00:55:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:55:00,0
335032,42,2013-07-31 00:56:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:56:00,0
335033,42,2013-07-31 00:57:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:57:00,0
335034,42,2013-07-31 00:58:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:58:00,0
335035,42,2013-07-31 00:59:00,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,2013-07-31,00:59:00,0