## DATASET FINAL DE CARGAS PARA SIMULACIÓN

In [472]:
import pandas as pd
import glob as gl
import matplotlib.pyplot as plt

In [473]:
#parámetros timestamp y fichero de salida
fecha = '2011-08-29' #28-11-2010 -> 28-11-2011
hora = 15 
out = "simtests/test_" + str(fecha) + "_" + str(hora) + ".csv" #nombre de ficheros de salida

In [474]:
#lectura de todos los dfs
path = gl.glob("dataset/nodes/loads/load_*.csv")
dfs = []

for file in path:
    dfs.append(pd.read_csv(file, low_memory=False))
    
df = pd.concat(dfs, ignore_index=True)

### Selección de instante temporal [2010-11-28, 2011-11-28)

In [475]:
subset = df[(df['datetime'] == fecha) & (df['h'] == hora)] 
subset.count() #tienen que ser 23 datos

timestamp                           18
datetime                            18
h                                   18
Beam Irradiance (W/m2)              18
Diffuse Irradiance (W/m2)           18
Ambient Temperature (C)             18
Plane of Array Irradiance (W/m2)    18
Cell Temperature (C)                18
DC Array Output (W)                 18
Pavg                                18
iid                                 18
dif                                 18
dtype: int64

In [476]:
column_order = ['iid'] + [col for col in list(subset.columns) if col not in ['iid']] #reorden de columna iid
subset = subset[column_order]
subset = subset.sort_values(by = 'iid')
subset

,iid,timestamp,datetime,h,Beam Irradiance (W/m2),Diffuse Irradiance (W/m2),Ambient Temperature (C),Plane of Array Irradiance (W/m2),Cell Temperature (C),DC Array Output (W),Pavg,dif
6326,1,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,316.215283,323.234717
115081,2,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,592.869966,46.580034
154538,3,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,947.401067,-307.951067
169444,5,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,697.851797,-58.401797
195130,8,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,194.886847,444.563153
205734,9,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,271.812355,367.637645
18085,10,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,361.505067,277.944933
27643,11,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,523.177220,116.272780
36345,12,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,258.485517,380.964483
44920,13,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,147.523655,491.926345
65886,15,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,356.401883,283.048117
72953,16,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,244.993568,394.456432
94160,18,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,162.053143,477.396857
105618,19,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,930.142950,-290.692950
123354,20,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,1218.010000,-578.560000
131310,21,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,350.931967,288.518033
140597,22,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,88.913583,550.536417
146772,23,2011-08-29 15:00:00,2011-08-29,15,39,176,23.4,201.253,31.579,639.45,1241.186193,-601.736193

In [477]:
if subset.shape[0] == 23 and not subset.empty: #23 filas con datos
    subset.to_csv(out, index=False)