## DATASET FINAL DE CARGAS PARA SIMULACIÓN

In [130]:
import pandas as pd
import glob as gl
import matplotlib.pyplot as plt

In [136]:
#parámetros timestamp y fichero de salida
fecha = '2010-11-28' #28-11-2010 -> 28-11-2011
hora = 11 
out = "simtests/" + str(hora) + "/test_" + str(fecha) + "_" + str(hora) + ".csv" #nombre de ficheros de salida

In [137]:
#lectura de todos los dfs
path = gl.glob("dataset/nodes/loads/load_*.csv")
dfs = []

for file in path:
    dfs.append(pd.read_csv(file, low_memory=False))
    
df = pd.concat(dfs, ignore_index=True)

### Selección de instante temporal [2010-11-28, 2011-11-28)

In [138]:
subset = df[(df['datetime'] == fecha) & (df['h'] == hora)] 
subset.count() #tienen que ser 23 datos

timestamp                           23
datetime                            23
h                                   23
Beam Irradiance (W/m2)              23
Diffuse Irradiance (W/m2)           23
Ambient Temperature (C)             23
Plane of Array Irradiance (W/m2)    23
Cell Temperature (C)                23
DC Array Output (W)                 23
Pavg                                23
iid                                 23
dif                                 23
dtype: int64

In [139]:
column_order = ['iid'] + [col for col in list(subset.columns) if col not in ['iid']] #reorden de columna iid
subset = subset[column_order]
subset = subset.sort_values(by = 'iid')
subset

,iid,timestamp,datetime,h,Beam Irradiance (W/m2),Diffuse Irradiance (W/m2),Ambient Temperature (C),Plane of Array Irradiance (W/m2),Cell Temperature (C),DC Array Output (W),Pavg,dif
11,1,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,61.552930,1800.905070
108641,2,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,117.253543,1745.204457
148195,3,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,1102.670500,759.787500
157629,4,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,109.465503,1752.992497
163151,5,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,856.760767,1005.697233
174585,6,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,256.816633,1605.641367
183048,7,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,61.827608,1800.630392
188859,8,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,723.741367,1138.716633
199636,9,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,227.491995,1634.966005
11625,10,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,105.279693,1757.178307
21253,11,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,169.729095,1692.728905
30203,12,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,268.250850,1594.207150
38750,13,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,156.132250,1706.325750
49816,14,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,460.927133,1401.530867
59711,15,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,1028.181150,834.276850
66668,16,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,185.879867,1676.578133
78214,17,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,1571.685217,290.772783
87969,18,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,1059.538367,802.919633
99492,19,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,453.987683,1408.470317
117332,20,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,195.589717,1666.868283
125058,21,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,216.953200,1645.504800
134275,22,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,62.895125,1799.562875
140806,23,2010-11-28 11:00:00,2010-11-28,11,559,114,17.4,574.209,40.944,1862.458,1727.284333,135.173667

In [135]:
if subset.shape[0] == 23 and not subset.empty: #23 filas con datos
    subset.to_csv(out, index=False)
else:
    subset.to_csv(out, index=False)